config/routes.rb
Matcher::Application.routes.draw do
  devise_for :admins

  devise_for :research_users

  devise_for :users

  resources :projects

  get "home/index"

  get "home/researchers"
  
  get "home/students"
  
  get "home/projects"
  
  get "home/positions"

  resources :departments, only: [:show], defaults: {format: :json}

  resources :paid_undergrad_positions

  resources :unpaid_undergrad_positions
  
  resources :paid_grad_positions

  resources :unpaid_grad_positions
  
  resources :post_doc

  resources :project_surveys do
  	resources :paid_undergrad_positions
		resources :unpaid_undergrad_positions
	end

  resources :student_profiles

  root :to => 'home#index', :as => 'home'

end

app/models/unpaid_undergrad_position.rb
class UnpaidUndergradPosition < ActiveRecord::Base
  attr_accessible :academic_level, :deliverables, :desired_classes, 
  :desired_skills, :job_description, :minimum_gpa, :record_begin, :record_end, 
  :weekly_time_commitment, :work_period, :project_survey_id, :academic_credit
  
  #project_survey = ProjectSurvey.new
 	#validates :desiredClasses, :presence => true
 
  
  belongs_to :project_survey
  belongs_to :project
  
end

app/controllers/unpaid_undergrad_positions_controller.rb
class UnpaidUndergradPositionsController < ApplicationController
  # GET /unpaid_undergrad_positions
  # GET /unpaid_undergrad_positions.json
  def index
    @unpaid_undergrad_positions = UnpaidUndergradPosition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @unpaid_undergrad_positions }
    end
  end

  # GET /unpaid_undergrad_positions/1
  # GET /unpaid_undergrad_positions/1.json
  def show
  	@project_survey = ProjectSurvey.find(params[:project_survey_id])
    @unpaid_undergrad_position = UnpaidUndergradPosition.where( :project_survey_id => @project_survey.id ).first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unpaid_undergrad_position }
    end
  end

  # GET /unpaid_undergrad_positions/new
  # GET /unpaid_undergrad_positions/new.json
  def new
    @unpaid_undergrad_position = UnpaidUndergradPosition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unpaid_undergrad_position }
    end
  end

  # GET /unpaid_undergrad_positions/1/edit
  def edit
    @unpaid_undergrad_position = UnpaidUndergradPosition.find(params[:id])
  end

  # POST /unpaid_undergrad_positions
  # POST /unpaid_undergrad_positions.json
  def create
  
    @unpaid_undergrad_position = UnpaidUndergradPosition.new(params[:unpaid_undergrad_position])

    respond_to do |format|
      if @unpaid_undergrad_position.save
        format.html { redirect_to @unpaid_undergrad_position, notice: 'Unpaid undergrad position was successfully created.' }
        format.json { render json: @unpaid_undergrad_position, status: :created, location: @unpaid_undergrad_position }
      else
        format.html { render action: "new" }
        format.json { render json: @unpaid_undergrad_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /unpaid_undergrad_positions/1
  # PUT /unpaid_undergrad_positions/1.json
  def update
  	
    @unpaid_undergrad_position = UnpaidUndergradPosition.find(params[:id])

    respond_to do |format|
      if @unpaid_undergrad_position.update_attributes(params[:unpaid_undergrad_position])
        format.html { redirect_to @unpaid_undergrad_position, notice: 'Unpaid undergrad position was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unpaid_undergrad_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unpaid_undergrad_positions/1
  # DELETE /unpaid_undergrad_positions/1.json
  def destroy
    @unpaid_undergrad_position = UnpaidUndergradPosition.find(params[:id])
    @unpaid_undergrad_position.destroy

    respond_to do |format|
      format.html { redirect_to unpaid_undergrad_positions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/unpaid_undergrad_positions_helper.rb
module UnpaidUndergradPositionsHelper
end

app/views/unpaid_undergrad_positions/_unpaid_undergrad_form.html.erb
<%= form_for(@unpaid_undergrad_position) do |f| %>
  <% if @unpaid_undergrad_position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unpaid_undergrad_position.errors.count, "error") %> prohibited this unpaid_undergrad_position from being saved:</h2>

      <ul>
      <% @unpaid_undergrad_position.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :workPeriod %><br />
    <%= f.text_field :workPeriod %>
  </div>
  <div class="field">
    <%= f.label :weeklyTimeCommitment %><br />
    <%= f.text_field :weeklyTimeCommitment %>
  </div>
  <div class="field">
    <%= f.label :deliverables %><br />
    <%= f.text_area :deliverables %>
  </div>
  <div class="field">
    <%= f.label :desiredSkills %><br />
    <%= f.text_area :desiredSkills %>
  </div>
  <div class="field">
    <%= f.label :desiredClasses %><br />
    <%= f.text_area :desiredClasses %>
  </div>
  <div class="field">
    <%= f.label :recordBegin %><br />
    <%= f.datetime_select :recordBegin %>
  </div>
  <div class="field">
    <%= f.label :recordEnd %><br />
    <%= f.datetime_select :recordEnd %>
  </div>
  <div class="field">
    <%= f.label :minimumGPA %><br />
    <%= f.text_field :minimumGPA %>
  </div>
  <div class="field">
    <%= f.label :academicLevel %><br />
    <%= f.text_field :academicLevel %>
  </div>
  <div class="field">
    <%= f.label :jobDescription %><br />
    <%= f.text_area :jobDescription %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unpaid_undergrad_positions/edit.html.erb
<h1>Editing unpaid_undergrad_position</h1>

<%= render 'form' %>

<%= link_to 'Show', @unpaid_undergrad_position %> |
<%= link_to 'Back', unpaid_undergrad_positions_path %>

app/views/unpaid_undergrad_positions/index.html.erb
<h1>Listing unpaid_undergrad_positions</h1>

<table>
  <tr>
    <th>Workperiod</th>
    <th>Weeklytimecommitment</th>
    <th>Deliverables</th>
    <th>Desiredskills</th>
    <th>Desiredclasses</th>
    <th>Recordbegin</th>
    <th>Recordend</th>
    <th>Minimumgpa</th>
    <th>Academiclevel</th>
    <th>Jobdescription</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @unpaid_undergrad_positions.each do |unpaid_undergrad_position| %>
  <tr>
    <td><%= unpaid_undergrad_position.workPeriod %></td>
    <td><%= unpaid_undergrad_position.weeklyTimeCommitment %></td>
    <td><%= unpaid_undergrad_position.deliverables %></td>
    <td><%= unpaid_undergrad_position.desiredSkills %></td>
    <td><%= unpaid_undergrad_position.desiredClasses %></td>
    <td><%= unpaid_undergrad_position.recordBegin %></td>
    <td><%= unpaid_undergrad_position.recordEnd %></td>
    <td><%= unpaid_undergrad_position.minimumGPA %></td>
    <td><%= unpaid_undergrad_position.academicLevel %></td>
    <td><%= unpaid_undergrad_position.jobDescription %></td>
    <td><%= link_to 'Show', unpaid_undergrad_position %></td>
    <td><%= link_to 'Edit', edit_unpaid_undergrad_position_path(unpaid_undergrad_position) %></td>
    <td><%= link_to 'Destroy', unpaid_undergrad_position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Unpaid undergrad position', new_unpaid_undergrad_position_path %>

app/views/unpaid_undergrad_positions/new.html.erb
<h1>New unpaid_undergrad_position</h1>

<%= render 'form' %>

<%= link_to 'Back', unpaid_undergrad_positions_path %>

app/views/unpaid_undergrad_positions/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Project Title:</b>
  <%= @project_survey.projectTitle %>
</p>
<p>
  <b>Research Area:</b>
  <%= @project_survey.researchArea %>
</p>
<p>
  <b>Department:</b>
  <%= @project_survey.department %>
</p>
<p>
  <b>Project Description:</b>
  <%= @project_survey.projectDescription %>
</p>
  <b>Contact Name:</b>
  <%= @project_survey.researcher %>
</p>
<p>
  <b>Email:</b>
  <%= @project_survey.email %>
</p>
<p>
  <b>Work Period:</b>
  <%= @unpaid_undergrad_position.workPeriod %>
</p>

<p>
  <b>Weekly Time Commitment:</b>
  <%= @unpaid_undergrad_position.weeklyTimeCommitment %>
</p>

<p>
  <b>Deliverables:</b>
  <%= @unpaid_undergrad_position.deliverables %>
</p>

<p>
  <b>Desired Skills:</b>
  <%= @unpaid_undergrad_position.desiredSkills %>
</p>

<p>
  <b>Desired Classes:</b>
  <%= @unpaid_undergrad_position.desiredClasses %>
</p>

<p>
  <b>Position Posted On: </b>
  <%= @unpaid_undergrad_position.recordBegin %>
</p>

<p>
  <b>Application Deadline:</b>
  <%= @unpaid_undergrad_position.recordEnd %>
</p>

<p>
  <b>Minimum GPA:</b>
  <%= @unpaid_undergrad_position.minimumGPA %>
</p>

<p>
  <b>Academic Standing:</b>
  <%= @unpaid_undergrad_position.academicLevel %>
</p>

<p>
  <b>Job Description:</b>
  <%= @unpaid_undergrad_position.jobDescription %>
</p>


<%= link_to 'Edit', edit_unpaid_undergrad_position_path(@unpaid_undergrad_position) %> |
<%= link_to 'Back', project_surveys_path %>