config/routes.rb
Matcher::Application.routes.draw do
  devise_for :admins

  devise_for :research_users

  devise_for :users

  resources :projects

  get "home/index"

  get "home/researchers"
  
  get "home/students"
  
  get "home/projects"
  
  get "home/positions"

  resources :departments, only: [:show], defaults: {format: :json}

  resources :paid_undergrad_positions

  resources :unpaid_undergrad_positions
  
  resources :paid_grad_positions

  resources :unpaid_grad_positions
  
  resources :post_doc

  resources :project_surveys do
  	resources :paid_undergrad_positions
		resources :unpaid_undergrad_positions
	end

  resources :student_profiles

  root :to => 'home#index', :as => 'home'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@project_surveys = ProjectSurvey.where( :research_user_id => current_research_user )

  end
  
  def researchers
  	if admin_signed_in?
 	 		@researchers = ResearchUser.all
		else
			redirect_to :home, notice: 'Access Denied.' 
  	end
	end
	
	def students
  	if admin_signed_in?
 	 		@students = User.all
		else
			redirect_to :home, notice: 'Access Denied.' 
  	end
	end 
	
	def projects
  	if admin_signed_in?
 	 		@projects = ProjectSurvey.all
		else
			redirect_to :home, notice: 'Access Denied.' 
  	end
	end 
	
	def positions
  	if admin_signed_in?
 	 		@unpaid_undergrad_positions = UnpaidUndergradPosition.all
 	 		@paid_undergrad_positions = PaidUndergradPosition.all
 	 		@unpaid_grad_positions = UnpaidGradPosition.all
 	 		@paid_grad_positions = PaidGradPosition.all
 	 		@post_doc_positions = PostDoc.all
		else
			redirect_to :home, notice: 'Access Denied.' 
  	end
	end   

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_edit_project_form.html.erb
<fieldset>
	

  
 
  



</div>
</fieldset>

app/views/home/_paid_undergrad_form.html.erb
 <fieldset>
  <div class="field">
    <%= f.label "Is this position posted on UNM jobs?" %><br />
    <%= f.text_field :unmJobs,:class => 'textField' %>
  </div>
  <div class="field">
    <%= f.label "If so, what is the posting number?" %><br />
    <%= f.text_field :postingNumber,:class => 'textField' %>
  </div>
  <div class="field">
    <%= f.label "Position Title" %><br />
    <%= f.text_field :positionTitle,:class => 'textField' %>
  </div>
  <div class="field">
    <%= f.label "Work Period" %><br />
    <%= f.text_field :workPeriod,:class => 'textField' %>
  </div>
  <div class="field">
    <%= f.label "Hours per week" %><br />
    <%= f.text_field :weeklyTimeCommitment,:class => 'textField' %>
  </div>
  <div class="field">
    <%= f.label "Desired Skills" %><br />
    <%= f.text_area :desiredSkills,:class => 'textArea' %>
  </div>
  <div class="field">
    <%= f.label "Desired Classes" %><br />
    <%= f.text_area :desiredClasses,:class => 'textArea' %>
  </div>
  <div class="field">
    <%= f.label "When should this position be posted?" %><br />
    <%= f.date_select :recordBegin %>
  </div>
  <div class="field">
    <%= f.label "What is the application deadline?" %><br />
    <%= f.date_select :recordEnd %>
  </div>
  <div class="field">
    <%= f.label "Minimum GPA" %><br />
    <%= f.text_field :minimumGPA,:class => 'textField' %>
  </div>
  <div class="field">
    <%= f.label "Desired Academic Standing" %><br />
    <%= f.text_field :academicLevel,:class => 'textField' %>
  </div>
  <div class="field">
    <%= f.label "General Job Description" %><br />
    <%= f.text_area :jobDescription,:class => 'textArea' %>
  </div>

</fieldset>

app/views/home/_unpaid_undergrad_form.html.erb
<fieldset>
	<div class="field">
		<%= f.label :workPeriod, "Work Period" %><br />
   	<%= f.text_field :workPeriod,:class => 'textField' %>
  <div class="field">
    <%= f.label "Weekly Time Commitment" %><br />
    <%= f.text_field :weeklyTimeCommitment,:class => 'textField' %>
  </div>	
  <div class="field">
    <%= f.label "Desired Skills" %><br />
    <%= f.text_area :desiredSkills, :class => 'textArea' %>
  </div>
  <div class="field">
    <%= f.label "Desired Classes" %><br />
    <%= f.text_area :desiredClasses,:class => 'textArea' %>
  </div>
  <div class="field">
    <%= f.label "When Should this opening be Posted?" %><br />
    <%= f.date_select :recordBegin %>
  </div>
  <div class="field">
    <%= f.label "When is the posting deadline?" %><br />
    <%= f.date_select :recordEnd%>
  </div>
  <div class="field">
    <%= f.label "Minimum GPA" %><br />
    <%= f.text_field :minimumGPA,:class => 'textField' %>
  </div>
  <div class="field">
    <%= f.label "Desired Academic Standing" %><br />
    <%= f.text_field :academicLevel,:class => 'textField' %>
  </div>
  <div class="field">
    <%= f.label "General Job Description" %><br />
    <%= f.text_area :jobDescription,:class => 'textArea' %>
  </div>
</fieldset>
  	  	

app/views/home/index.html.erb
<% breadcrumb :home %>
<% width = "width:180px;" %>
<div id="wrap">
	<% if admin_signed_in? %>
		
		<div id="main">
			<%= button_to "View Projects", project_surveys_path, :method => "get", :style => width %>

			<%= button_to "Projects Table", home_projects_path, :method => "get", :style => width %>
			<%= button_to "Positions Table", home_positions_path, :method => "get", :style => width %>
		</div><!--End of "main"> -->
		
		<div id="sidebar">
			<%= button_to "View Scholars' Profiles", student_profiles_path, :method => "get", :style => width %>
			<%= button_to "Students Table", home_students_path, :method => "get", :style => width %>
			<%= button_to "Researchers Table", home_researchers_path, :method => "get", :style => width %>
		</div> <!-- End of "sidebar" -->

	
	<% elsif research_user_signed_in? %>

				<div id="lcell">
					<%= button_to "View Scholars' Profiles", student_profiles_path, :method => "get", :style => width %>
					<%= button_to "View Projects", project_surveys_path, :method => "get", :style => width %>
					<%= button_to "Submit New Project", new_project_survey_path, :method => "get", :style => width %>
					<%= button_to "Logout", destroy_research_user_session_path, method: :delete, :style => width %>
				</div>
				
				<div id="rcell">
					<p>
						<h5>View available students by department.</h5>
					</p>
					<div id="row">
						<h5>View current projects by department.</h5> 
					</div>
					<div id="row">
						<h5>Submit new project to the database.</h5> 
					</div>
					<div id="row">
						<h5>End this session.</h5> 
					</div>
				</div>
	
			<% if @project_surveys.length > 0 %>
				<div id="bottom">
					<hr>
					<h1>Your Current Projects:</h1>
					<table>
				<tr>
					<th>Project Title</th>
					<th>Project Description</th>

					<th>Show</th>
					<th>Edit</th>
					<th>Destroy</th>
				</tr>

			<% @project_surveys.each do |project_survey| %>
				<tr>
					<td><%= project_survey.project_title %></td>
					<td><%= project_survey.project_description %></td>
					<td><%= link_to 'Show', project_survey_path(project_survey) %></td>
					<td><%= link_to 'Edit', edit_project_survey_path(project_survey) %></td>
					<td><%= link_to 'Destroy', project_survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			<% end %>
			</table>

			<br />
				</div>
			<% end %> <!-- if @project_surveys -->

	<% elsif user_signed_in? %>
		<% if current_user.student_profile %>
			<h1>Welcome <%= current_user.student_profile.first_name %> <%= current_user.student_profile.last_name %> </h1>
		<% else %>
			<h1>Welcome New User, create a profile.</h1>
		<% end %>
		<div id="lcell">
			<% if current_user.student_profile %>
			<%= button_to "Edit Profile", edit_student_profile_path(current_user.student_profile.id), :method => "get", :style => width %>
		<% else %>
			<%= button_to "Create Profile", new_student_profile_path, :method => "get", :style => width %>
		<% end %>
			<%= button_to "View Projects", project_surveys_path, :method => "get", :style => width %>
			<%= button_to "Logout", destroy_user_session_path, method: :delete, :style => width %>

		</div>
				
		<div id="rcell">
			<p>
				<h5>Your profile will be viewed by hiring researchers.</h5>
			</p>
			<div id="row">
				<h5>View current projects by department.</h5> 
			</div>
			<div id="row">
				<h5>End this session.</h5> 
			</div>
			
		</div>
		
		<% if current_user.student_profile %>
			<% @student_profile = current_user.student_profile %>

			<div id="bottom">
				<br />
				<hr>
				<h1>Your Current Profile:</h1>
				<p>
					<b>First Name:</b>
					<%= @student_profile.first_name %>
				</p>

				<p>
					<b>Last Name:</b>
					<%= @student_profile.last_name %>
				</p>
				<p>
					<b>Email:</b>
					<%= @student_profile.email %>
				</p>

				<p>
					<b>Banner ID:</b>
					<%= @student_profile.unm_id %>
				</p>

				<p>
					<b>Phone Number:</b>
					<%= @student_profile.phone_number %>
				</p>

				<p>
					<b>Academic Standing:</b>
					<%= @student_profile.academic_level %>
				</p>

				<p>
					<b>Major:</b>
					<%= @student_profile.major %>
				</p>

				<p>
					<b>Minor:</b>
					<%= @student_profile.minor %>
				</p>

				<p>
					<b>Expected Graduation:</b>
					<%= @student_profile.expected_graduation.strftime("%m-%d-%Y") %>
				</p>

				<p>
					<b>Interests:</b>
					<%= @student_profile.interests %>
				</p>
				<hr>
			</div>
		<% end %>
	
	<% else %>
		<h1>UNM's Research Opportunity Database.</h1>
		<h4>Connecting students to research opportunities.</h4>
		<div id="lcell">
		<%= button_to "Researcher Sign Up", new_research_user_registration_path, :method => "get", :style => width %>
			<%= button_to "Student Sign Up", new_user_registration_path, :method => "get", :style => width %>
			<%= button_to "View Projects", project_surveys_path, :method => "get", :style => width %>
		</div>
				
		<div id="rcell">
			<p>
			<h5>Add your projects to the database.</h5> 	
			</p>
			<div id="row">
				<h5><%= link_to "Sign up", new_user_registration_path %> to add your profile to the database.</h5>
			</div>
			<div id="row">
				<h5>Browse the project database. For more information,<br /> <%= link_to "login", new_user_session_path %> or <%= link_to "sign up", new_user_registration_path %>.</h5>
			</div>
			
		</div>
	<% end %> <!-- End "if research_user_signed_in?" -->
	
</div> <!-- end of "wrap"-->

app/views/home/positions.html.erb
<% if @unpaid_undergrad_positions %>
				
				<h1>Unpaid Undergrad Positions:</h1>
					<table>
				<tr>
					<th>Department</th>
					<th>Lead Researcher</th>					
					<th>Project</th>
					<th>Destroy</th>
				</tr>

			<% @unpaid_undergrad_positions.each do |position| %>
				<% if position.project_survey %>
				<tr>
					<td><%= position.project_survey.department %></td>
					<td><%= position.project_survey.lead_researcher %></td>
					<td><%= link_to 'Project',project_survey_path(position.project_survey) %></td>
					<td> <%= link_to "Destroy", unpaid_undergrad_position_path(position), :confirm => "Are you sure?", :method => :delete %></td>
				</tr>
				<% end %>
	<% end %>
		</table>
<% end %><!-- If @ researchers -->
<br />
<% if @paid_undergrad_positions %>
				
				<h1>Paid Undergrad Positions:</h1>
					<table>
				<tr>
					<th>Department</th>
					<th>Lead Researcher</th>					
					<th>Project</th>
					<th>Destroy</th>
				</tr>

			<% @paid_undergrad_positions.each do |position| %>
				<% if position.project_survey %>
				<tr>
					<td><%= position.project_survey.department %></td>
					<td><%= position.project_survey.lead_researcher %></td>
					<td><%= link_to 'Project',project_survey_path(position.project_survey) %></td>
					<td> <%= link_to "Destroy", paid_undergrad_position_path(position), :confirm => "Are you sure?", :method => :delete %></td>
				</tr>
				<% end %>
	<% end %>
		</table>
<% end %><!-- If @ researchers -->
<br />
<% if @unpaid_grad_positions %>
				
				<h1>Unpaid Grad Positions:</h1>
					<table>
				<tr>
					<th>Department</th>
					<th>Lead Researcher</th>					
					<th>Project</th>
					<th>Destroy</th>
				</tr>

			<% @unpaid_grad_positions.each do |position| %>
				<% if position.project_survey %>
				<tr>
					<td><%= position.project_survey.department %></td>
					<td><%= position.project_survey.lead_researcher %></td>
					<td><%= link_to 'Project',project_survey_path(position.project_survey) %></td>
					<td> <%= link_to "Destroy", unpaid_grad_position_path(position), :confirm => "Are you sure?", :method => :delete %></td>
				</tr>
				<% end %>
	<% end %>
		</table>
<% end %><!-- If @ researchers -->
<br />
<% if @paid_grad_positions %>
				
				<h1>Paid Grad Positions:</h1>
					<table>
				<tr>
					<th>Department</th>
					<th>Lead Researcher</th>					
					<th>Project</th>
					<th>Destroy</th>
				</tr>

			<% @paid_grad_positions.each do |position| %>
				<% if position.project_survey %>
				<tr>
					<td><%= position.project_survey.department %></td>
					<td><%= position.project_survey.lead_researcher %></td>
					<td><%= link_to 'Project',project_survey_path(position.project_survey) %></td>
					<td> <%= link_to "Destroy", paid_grad_position_path(position), :confirm => "Are you sure?", :method => :delete %></td>
				</tr>
				<% end %>
	<% end %>
		</table>
<% end %><!-- If @ researchers -->
<br />
<% if @post_doc_positions %>
				
				<h1>Postdoc Positions:</h1>
					<table>
				<tr>
					<th>Department</th>
					<th>Lead Researcher</th>					
					<th>Project</th>
					<th>Destroy</th>
				</tr>

			<% @post_doc_positions.each do |position| %>
				<% if position.project_survey %>
				<tr>
					<td><%= position.project_survey.department %></td>
					<td><%= position.project_survey.lead_researcher %></td>
					<td><%= link_to 'Project',project_survey_path(position.project_survey) %></td>
					<td> <%= link_to "Destroy", post_doc_path(position), :confirm => "Are you sure?", :method => :delete %></td>
				</tr>
				<% end %>
	<% end %>
		</table>
<% end %><!-- If @ researchers -->

	

app/views/home/projects.html.erb
<% if @projects %>
				
				<h1>Projects:</h1>
					<table>
				<tr>
					<th>Lead Researcher</th>
					<th>Department</th>
					<th>View Project</th>
					<th>Destroy</th>
				</tr>

			<% @projects.each do |project| %>
				<tr>
					<td><%= project.lead_researcher %></td>
					<td><%= project.department %></td>
					<td><%= link_to 'Project',project_survey_path(project) %></td>
					<td> <%= link_to "Destroy", project_survey_path(project), :confirm => "Are you sure?", :method => :delete %></td>
				</tr>
	<% end %>
		</table>
<% end %><!-- If @ researchers -->

	

app/views/home/researchers.html.erb
<% if @researchers %>
				<h1>Researcher Accounts:</h1>
					<table>
				<tr>
					<th>First Name</th>
					<th>Last Name</th>
					<th>Number of Projects</th>
					<th>Destroy</th>
				</tr>

			<% @researchers.each do |researcher| %>
				<tr>
					<td><%= researcher.first_name %></td>
					<td><%= researcher.last_name %></td>
					<td><%= researcher.project_surveys.size %></td>
					<td> <%= link_to "Destroy", research_user_registration_path(researcher), :confirm => "Are you sure?", :method => :delete %></td>
				</tr>
	<% end %>
		</table>
<% end %><!-- If @ researchers -->

	

app/views/home/students.html.erb
<% if @students %>
				
				<h1>Student Accounts:</h1>
					<table>
				<tr>
					<th>First Name</th>
					<th>Last Name</th>
					<th>View Profile</th>
					<th>Destroy</th>
				</tr>

			<% @students.each do |student| %>
				<% profile = student.student_profile %>
				<% if profile %>
				<tr>
					<td><%= profile.first_name %></td>
					<td><%= profile.last_name %></td>
					<td><%= link_to 'Profile',student_profile_path(profile) %></td>
					<td> <%= link_to "Destroy", user_registration_path(student), :confirm => "Are you sure?", :method => :delete %></td>
				</tr>
				<% end %>	
	<% end %>
		</table>
<% end %><!-- If @ researchers -->

	