config/routes.rb
Matcher::Application.routes.draw do
  devise_for :admins

  devise_for :research_users

  devise_for :users

  resources :projects

  get "home/index"

  get "home/researchers"
  
  get "home/students"
  
  get "home/projects"
  
  get "home/positions"

  resources :departments, only: [:show], defaults: {format: :json}

  resources :paid_undergrad_positions

  resources :unpaid_undergrad_positions
  
  resources :paid_grad_positions

  resources :unpaid_grad_positions
  
  resources :post_doc

  resources :project_surveys do
  	resources :paid_undergrad_positions
		resources :unpaid_undergrad_positions
	end

  resources :student_profiles

  root :to => 'home#index', :as => 'home'

end

app/models/paid_undergrad_position.rb
class PaidUndergradPosition < ActiveRecord::Base
  attr_accessible :academic_level, :deliverables, :desired_classes, 
  :desired_skills, :job_description, :minimum_gpa, :position_title, 
  :posting_number, :record_begin, :record_end, :unm_jobs, :weekly_time_commitment, 
  :work_period, :project_survey_id
  
  belongs_to :project_survey
  belongs_to :project	
end

app/controllers/paid_undergrad_positions_controller.rb
class PaidUndergradPositionsController < ApplicationController
  # GET /paid_undergrad_positions
  # GET /paid_undergrad_positions.json
  def index
    @paid_undergrad_positions = PaidUndergradPosition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @paid_undergrad_positions }
    end
  end

  # GET /paid_undergrad_positions/1
  # GET /paid_undergrad_positions/1.json
  def show
    @paid_undergrad_position = PaidUndergradPosition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @paid_undergrad_position }
    end
  end

  # GET /paid_undergrad_positions/new
  # GET /paid_undergrad_positions/new.json
  def new
    @paid_undergrad_position = PaidUndergradPosition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @paid_undergrad_position }
    end
  end

  # GET /paid_undergrad_positions/1/edit
  def edit
    @paid_undergrad_position = PaidUndergradPosition.find(params[:id])
  end

  # POST /paid_undergrad_positions
  # POST /paid_undergrad_positions.json
  def create
    @project_survey = ProjectSurvey.find(params[:project_survey_id])
    @paid_undergrad_position = @project_survey.paid_grad_position.create!(params[:paid_undergrad_position])

    respond_to do |format|
      if @paid_undergrad_position.save
        format.html { redirect_to @paid_undergrad_position, notice: 'Paid undergrad position was successfully created.' }
        format.json { render json: @paid_undergrad_position, status: :created, location: @paid_undergrad_position }
      else
        format.html { render action: "new" }
        format.json { render json: @paid_undergrad_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /paid_undergrad_positions/1
  # PUT /paid_undergrad_positions/1.json
  def update
    @paid_undergrad_position = PaidUndergradPosition.find(params[:id])

    respond_to do |format|
      if @paid_undergrad_position.update_attributes(params[:paid_undergrad_position])
        format.html { redirect_to @paid_undergrad_position, notice: 'Paid undergrad position was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @paid_undergrad_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paid_undergrad_positions/1
  # DELETE /paid_undergrad_positions/1.json
  def destroy
    @paid_undergrad_position = PaidUndergradPosition.find(params[:id])
    @paid_undergrad_position.destroy

    respond_to do |format|
      format.html { redirect_to paid_undergrad_positions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/paid_undergrad_positions_helper.rb
module PaidUndergradPositionsHelper
end

app/views/paid_undergrad_positions/_form.html.erb
<%= form_for(@paid_undergrad_position) do |f| %>
  <% if @paid_undergrad_position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paid_undergrad_position.errors.count, "error") %> prohibited this paid_undergrad_position from being saved:</h2>

      <ul>
      <% @paid_undergrad_position.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :unmJobs %><br />
    <%= f.text_field :unmJobs %>
  </div>
  <div class="field">
    <%= f.label :postingNumber %><br />
    <%= f.text_field :postingNumber %>
  </div>
  <div class="field">
    <%= f.label :positionTitle %><br />
    <%= f.text_field :positionTitle %>
  </div>
  <div class="field">
    <%= f.label :workPeriod %><br />
    <%= f.text_field :workPeriod %>
  </div>
  <div class="field">
    <%= f.label :weeklyTimeCommitment %><br />
    <%= f.text_field :weeklyTimeCommitment %>
  </div>
  <div class="field">
    <%= f.label :deliverables %><br />
    <%= f.text_area :deliverables %>
  </div>
  <div class="field">
    <%= f.label :desiredSkills %><br />
    <%= f.text_area :desiredSkills %>
  </div>
  <div class="field">
    <%= f.label :desiredClasses %><br />
    <%= f.text_area :desiredClasses %>
  </div>
  <div class="field">
    <%= f.label :recordBegin %><br />
    <%= f.datetime_select :recordBegin %>
  </div>
  <div class="field">
    <%= f.label :recordEnd %><br />
    <%= f.datetime_select :recordEnd %>
  </div>
  <div class="field">
    <%= f.label :minimumGPA %><br />
    <%= f.text_field :minimumGPA %>
  </div>
  <div class="field">
    <%= f.label :academicLevel %><br />
    <%= f.text_field :academicLevel %>
  </div>
  <div class="field">
    <%= f.label :jobDescription %><br />
    <%= f.text_area :jobDescription %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paid_undergrad_positions/edit.html.erb
<h1>Editing paid_undergrad_position</h1>

<%= render 'form' %>

<%= link_to 'Show', @paid_undergrad_position %> |
<%= link_to 'Back', paid_undergrad_positions_path %>

app/views/paid_undergrad_positions/index.html.erb
<h1>Listing paid_undergrad_positions</h1>

<table>
  <tr>
    <th>Unmjobs</th>
    <th>Postingnumber</th>
    <th>Positiontitle</th>
    <th>Workperiod</th>
    <th>Weeklytimecommitment</th>
    <th>Deliverables</th>
    <th>Desiredskills</th>
    <th>Desiredclasses</th>
    <th>Recordbegin</th>
    <th>Recordend</th>
    <th>Minimumgpa</th>
    <th>Academiclevel</th>
    <th>Jobdescription</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @paid_undergrad_positions.each do |paid_undergrad_position| %>
  <tr>
    <td><%= paid_undergrad_position.unmJobs %></td>
    <td><%= paid_undergrad_position.postingNumber %></td>
    <td><%= paid_undergrad_position.positionTitle %></td>
    <td><%= paid_undergrad_position.workPeriod %></td>
    <td><%= paid_undergrad_position.weeklyTimeCommitment %></td>
    <td><%= paid_undergrad_position.deliverables %></td>
    <td><%= paid_undergrad_position.desiredSkills %></td>
    <td><%= paid_undergrad_position.desiredClasses %></td>
    <td><%= paid_undergrad_position.recordBegin %></td>
    <td><%= paid_undergrad_position.recordEnd %></td>
    <td><%= paid_undergrad_position.minimumGPA %></td>
    <td><%= paid_undergrad_position.academicLevel %></td>
    <td><%= paid_undergrad_position.jobDescription %></td>
    <td><%= link_to 'Show', paid_undergrad_position %></td>
    <td><%= link_to 'Edit', edit_paid_undergrad_position_path(paid_undergrad_position) %></td>
    <td><%= link_to 'Destroy', paid_undergrad_position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Paid undergrad position', new_paid_undergrad_position_path %>

app/views/paid_undergrad_positions/new.html.erb
<h1>New paid_undergrad_position</h1>

<%= render 'form' %>

<%= link_to 'Back', paid_undergrad_positions_path %>

app/views/paid_undergrad_positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Unmjobs:</b>
  <%= @paid_undergrad_position.unmJobs %>
</p>

<p>
  <b>Postingnumber:</b>
  <%= @paid_undergrad_position.postingNumber %>
</p>

<p>
  <b>Positiontitle:</b>
  <%= @paid_undergrad_position.positionTitle %>
</p>

<p>
  <b>Workperiod:</b>
  <%= @paid_undergrad_position.workPeriod %>
</p>

<p>
  <b>Weeklytimecommitment:</b>
  <%= @paid_undergrad_position.weeklyTimeCommitment %>
</p>

<p>
  <b>Deliverables:</b>
  <%= @paid_undergrad_position.deliverables %>
</p>

<p>
  <b>Desiredskills:</b>
  <%= @paid_undergrad_position.desiredSkills %>
</p>

<p>
  <b>Desiredclasses:</b>
  <%= @paid_undergrad_position.desiredClasses %>
</p>

<p>
  <b>Recordbegin:</b>
  <%= @paid_undergrad_position.recordBegin %>
</p>

<p>
  <b>Recordend:</b>
  <%= @paid_undergrad_position.recordEnd %>
</p>

<p>
  <b>Minimumgpa:</b>
  <%= @paid_undergrad_position.minimumGPA %>
</p>

<p>
  <b>Academiclevel:</b>
  <%= @paid_undergrad_position.academicLevel %>
</p>

<p>
  <b>Jobdescription:</b>
  <%= @paid_undergrad_position.jobDescription %>
</p>


<%= link_to 'Edit', edit_paid_undergrad_position_path(@paid_undergrad_position) %> |
<%= link_to 'Back', paid_undergrad_positions_path %>