config/routes.rb
Matcher::Application.routes.draw do
  devise_for :admins

  devise_for :research_users

  devise_for :users

  resources :projects

  get "home/index"

  get "home/researchers"
  
  get "home/students"
  
  get "home/projects"
  
  get "home/positions"

  resources :departments, only: [:show], defaults: {format: :json}

  resources :paid_undergrad_positions

  resources :unpaid_undergrad_positions
  
  resources :paid_grad_positions

  resources :unpaid_grad_positions
  
  resources :post_doc

  resources :project_surveys do
  	resources :paid_undergrad_positions
		resources :unpaid_undergrad_positions
	end

  resources :student_profiles

  root :to => 'home#index', :as => 'home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US" xmlns:xhtml="http://www.w3.org/1999/xhtml">
<head>
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  <title> Research Opportunity Database | The University of New Mexico</title>
  
  <meta content="Tue, 23 Apr 2013 10:44:49 -0440" name="date" />

	<meta content="suDeBu3cQ5JEfYn92UdyZqkDPVCRI3QFK4dbV1tzUNk" name="google-site-verification" />
	<link href="https://webcore.unm.edu/v1/images/unm.ico" rel="shortcut icon" />
	<link href="https://webcore.unm.edu/v1/css/styles.php" media="screen" rel="stylesheet" 			type="text/css" />
	<link href="https://webcore.unm.edu/v1/css/styles.php?media=print" media="print" rel="stylesheet" type="text/css" />
	<link href="common/css/site.css" media="screen" rel="stylesheet" type="text/css" />
	<!--[if lt IE 7]>
	<link href="https://webcore.unm.edu/v1/css/ie.css" rel="stylesheet" type="text/css" media="screen" />
	<![endif]-->
	<script src="https://webcore.unm.edu/v1/javascript/jquery.min.js" type="text/javascript"></	script>
	<script src="https://webcore.unm.edu/v1/javascript/unm_scripts.php" type="text/javascript" ></script>

<!-- Site Meta - put site specific css, javascript, etc. here-->
	<%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag 'jquery', 'application' %>
  <%= csrf_meta_tags %>
  
 <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44955950-1', 'unm.edu');
  ga('send', 'pageview');

</script>
</head>
<body>
<div id="unm_header">
<div class="header_content">
<div id="skipnav"><a accesskey="2" href="#content" tabindex="1">Skip to Main Content</a> <span class="hide">|</span> <a accesskey="1" href="http://www.unm.edu">UNM Homepage</a> <span class="hide">|</span> <a accesskey="0" href="http://www.unm.edu/accessibility.html">Accessibility Statement</a></div>
<div class="unm_header_title"><a href="http://www.unm.edu" title="The University of New Mexico">The University of New Mexico</a></div>
<div id="unm_header_links">
<ul title="global UNM navigation">
<li><a href="http://www.unm.edu/depart.html" title="UNM A to Z">UNM A-Z</a></li>
<li><a href="http://studentinfo.unm.edu" title="StudentInfo">StudentInfo</a></li>
<li><a href="http://fastinfo.unm.edu" title="FastInfo">FastInfo</a></li>
<li><a href="https://my.unm.edu" title="myUNM">myUNM</a></li>
<li><a href="http://directory.unm.edu" title="Directory">Directory</a></li>
</ul>
<form action="http://google.unm.edu/search" id="unm_search_form" method="get">
<fieldset><input name="site" type="hidden" value="UNM" /> <input name="client" type="hidden" value="UNM" /> <input name="proxystylesheet" type="hidden" value="UNM" /> <input name="output" type="hidden" value="xml_no_dtd" /> <input accesskey="4" alt="input search query here" class="search_query" id="unm_search_form_q" maxlength="255" name="q" title="input search query here" type="text" /> <input accesskey="s" alt="search now" class="search_button" id="unm_search_for_submit" name="submit" src="http://webcore.unm.edu/v1/images/search.gif" type="image" value="search" /></fieldset>
</form>
</div>
</div>
</div>
<div id="page">
  <div id="dept_header">
    <div id="dept_logo"><%= link_to image_tag('unm-logo.gif'), 'http://uresearch.unm.edu' %></div>  
  </div>
  <div class="col2" id="container">
    <div id="primary_aside">
    <div class="content">
      <div id="primary_aside_1"><ul class="slidemenu" id="dept_nav"><li><a href="/home/index.html">Home</a></li><li><a href="/project_surveys">View Projects</a></li><li><a  href="/users/sign_in">Student Sign In</a></li><li><a href="/research_users/sign_in">Researcher Sign In</a></li></ul></div>
      <div id="primary_aside_2" ></div>
      <div id="primary_aside_3" ></div>
			<div id="primary_aside_4"><div class="vcard leftnav_contact"><a class="fn organization-unit url" href="http://grad.unm.edu/graduate-programs/research.html">Graduate Research</a><p class="adr"><span class="extended-address">MSC 03 2180</span><br /><span class="extended-address">Humanities Bldg, Suite 107</span><br /><span class="street-address">1 University of New Mexico</span><br /><span class="locality">Albuquerque</span>, <abbr class="region" title="New Mexico">NM</abbr> <span class="postal-code">87131-0001</span></p><p><span class="tel"><span class="type hidden">Work</span> Phone: <span class="value">(505) 277-2711</span><br /></span><span class="tel"><span class="type hidden">Fax</span> Fax: <span class="value">(505) 277-7405</span><br /></span><span><a class="email" href="mailto:grad@unm.edu">grad@unm.edu</a></span></p></div></div>
      <div id="primary_aside_5"><div class="vcard leftnav_contact"><a class="fn organization-unit url" href="http://uresearch.unm.edu">Undergraduate Research</a><p class="adr"><span class="extended-address">MSC06 3680</span><br /><span class="extended-address">University Advisement &amp; Enrichment Center, University College Suite 180</span><br /><span class="street-address">1 University of New Mexico</span><br /><span class="locality">Albuquerque</span>, <abbr class="region" title="New Mexico">NM</abbr> <span class="postal-code">87131</span></p><p><span class="tel"><span class="type hidden">Work</span> Phone: <span class="value">505-277-0428</span><br /></span><span><a class="email" href="mailto:uresearch@unm.edu">uresearch@unm.edu</a></span></p></div></div>

    </div>
    </div>
    
    <div id="content_top">
  
				
      <div class="content">
<div id="bc" style="float:left;">
        <%= breadcrumbs :pretext => "",:separator => " &rsaquo; " %>
            			</div>
            			<div id="user_info" style="float:right;padding-right:20px;padding-bottom:2px;">
            			
       	<% if user_signed_in? && !research_user_signed_in? %>
  					Logged in as <strong><%= current_user.email %></strong>. 
  					
  					<% if current_user.student_profile  %>
  						<%= link_to 'Edit profile', edit_student_profile_path(current_user.student_profile.id) %>
  					<% else %>
  						<%= link_to 'Create profile', new_student_profile_path %>
  					<% end %>
  					 |
 						<%= link_to "Logout", destroy_user_session_path, method: :delete %>
			
			 <% end %>
			 		<% if !signed_in?  %>
  					<%= link_to "Student Sign In", new_user_session_path %> |
  					<%= link_to "Researcher Sign In", new_research_user_session_path %>
					<% end %>
			 <% if research_user_signed_in? %>
			 	<%= link_to "Logout", destroy_research_user_session_path, method: :delete %>
			 <% end %>

			 			 <% if admin_signed_in? %>
			 	<%= link_to "Logout", destroy_user_session_path, method: :delete %>
			 <% end %>
			 </div>
				<div id="content_hr" style="clear:both;">
        <hr style="color:#f00;">
        </div>

        
      </div>
    </div>
 
    <div id="content">

      <div class="content">
        <div id="before_default_1" ></div>
        <div id="before_default_2" ></div>
        <div id="before_default_3" ></div>
        <div id="before_default_4" ></div>
				  	
        	<p class="notice" style="color:green;"><%= notice %></p>
        	<% if alert %>
       			<p class="alert"><%= alert %></p>
       		<% end %>
					<%= yield %>
					

        <div id="after_default_1" ></div>
        <div id="after_default_2" ></div>
        <div id="after_default_3" ></div>
        <div id="after_default_4" ></div>
      </div>
    </div>
    <div id="secondary_aside">
    <div class="content">
      <div id="secondary_aside_1" ></div>
      <div id="secondary_aside_2" ></div>
      <div id="secondary_aside_3" ></div>
      <div id="secondary_aside_4" ></div>
    </div>
    </div>
  </div>
  <div id="footer"><div class="content"><p>&#169; The University of New Mexico, Albuquerque, NM 87131, (505) 277-0111 <br />
                	New Mexico's Flagship University
                 </p><ul id="unm_footer_links"><li><a href="http://www.unm.edu/accessibility.html">Accessibility</a></li><li><a href="http://www.unm.edu/legal.html">Legal</a></li><li><a href="http://www.unm.edu/contactunm.html">Contact UNM</a></li></ul></div></div>

</body>
</html>

app/views/layouts/old_application.html.erb
<% breadcrumb :home %>
<h1>Welcome to UNM's Undergraduate Research Opportunity Database</h1>
<div id="wrap">
  <!-- 	<% if user_signed_in? %>
  					Logged in as <strong><%= current_user.email %></strong>.
  					<%= link_to 'Edit profile', edit_user_registration_path %> |
 						<%= link_to "Logout", destroy_user_session_path, method: :delete %>
					<% else %>
  					<%= link_to "Sign up", new_user_registration_path %> |
  					<%= link_to "Login", new_user_session_path %>
					<% end %>-->	
	<div id="main">
	<!---!!!!!!!!!!!!!!!!!!!!!!_-->
		<%= button_to "View Projects", project_surveys_path, :method => "get", :style => "width:600px;"%>
		
	
	</div>
	<div id="sidebar" >
	<% if admin_signed_in? %>
		<%= button_to "View Scholars' Profiles", student_profiles_path, :method => "get" %>

	<%	elsif research_user_signed_in? && !user_signed_in? %>
		<%= button_to "Register Project", new_project_survey_path, :method => "get" %>
	<% elsif !research_user_signed_in? && !user_signed_in? %>
		<%= button_to "Register Project", new_research_user_session_path, :method => "get" %>
	<% end %>
	
		<% if user_signed_in? && !admin_signed_in? %>
		<% if current_user.student_profile %>
			<%= button_to "Edit Profile", edit_student_profile_path(current_user.student_profile.id), :method => "get" %>
		<% else %>
			<%= button_to "Create Profile", new_student_profile_path, :method => "get" %>
		<% end %>
	<% end %>
	</div>
	<div id ="bottom">
	
	</div>

</div>
<% if !user_signed_in? && !research_user_signed_in? %> 
	<div id="left">
			
		<h5>Feel free to browse the project database.<br /> For more information, <%= link_to "login", new_user_session_path %> <br />or <%= link_to "sign up", new_user_registration_path %>.</h5>
			
	</div>
	<div id="right">
		<% if research_user_signed_in? %>	
			<h5  style="padding-left:30px;">If you are a researcher who would like to add your project to the database.</h5>
		<% elsif admin_signed_in? %>
			<h5 style="padding-left:50px;">Browse the project database for available positions.</h5>
		<% else %>
			<h5  style="padding-left:30px;">If you are a researcher who would like to add your project to the database.</h5>
		<% end %>	
	</div>
<% else %>
	<div id="left">
			<% if !admin_signed_in? %>
		<h5>Browse the project database for available positions.</h5>
			
	</div>
	<div id="right">
				<% if user_signed_in? %>
					<h5 style="padding-left:20px;">Your profile will be available for hiring researchers to view.</h5>
				<% elsif research_user_signed_in? %>
					<h5  style="padding-left:30px;">Post a new project to the database.</h5>		
				<% end %>	
			<% end %>	
	</div>
<% end %>

<div id="baja">
	<div id="main">
	<!--<% if admin_signed_in? %> 
		<%= button_to "Admin Console", project_surveys_path, :method => "get" %>
	<% end %> -->
	<% if research_user_signed_in? %>
		<%= button_to "View Scholars' Profiles", student_profiles_path, :method => "get" %>
	<% end %>
	<% if user_signed_in? && !admin_signed_in? %>
		<% if current_user.student_profile %>
			<%= button_to 'Delete My Profile', student_profile_path(current_user.student_profile.id), method: :delete, data: { confirm: 'Are you sure you want to delete your profile?' } %>
		<% end %>
	<% end %>
	</div>
	
	<div id="right" style="padding-left:102px;">
		<% if research_user_signed_in? %>
			<%= button_to "Logout", destroy_research_user_session_path, method: :delete %>	
		<% end %>

		<% if user_signed_in? %>
			<%= button_to "Logout", destroy_user_session_path, method: :delete %>	
		<% end %>
	</div>
	<% if research_user_signed_in? %>
		<% if @project_surveys.length > 0 %>
			<div id="bottom">
				<hr>
				<h1>My Current Projects:</h1>
				<table>
			<tr>
				<th>Project Title</th>
				<th>Project Description</th>

				<th>Show</th>
				<th>Edit</th>
				<th>Destroy</th>
			</tr>

		<% @project_surveys.each do |project_survey| %>
			<tr>
				<td><%= project_survey.project_title %></td>
				<td><%= project_survey.project_description %></td>
				<td><%= link_to 'Show', project_survey_path(project_survey) %></td>
				<td><%= link_to 'Edit', edit_project_survey_path(project_survey) %></td>
				<td><%= link_to 'Destroy', project_survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
		</table>

		<br />
			</div>
		<% end %> <!-- if @project_surveys -->
	<% end %>
</div>